services:
  php:
    image: tugboatqa/php:7.2-apache
    default: true
    depends: mariadb
    commands:
      init:
        # Enable Apache 'rewrite' module for clean URLs.
        - a2enmod rewrite
        # Get the api.backdropcms.org site code.
        - cd $TUGBOAT_ROOT && git clone https://github.com/BWPanda/api.backdropcms.org.git
        # Checkout the branch with the PR to test.
        - cd $TUGBOAT_ROOT/api.backdropcms.org && git checkout issue-66-2
        # Link the document root to the expected path.
        - ln -snf $TUGBOAT_ROOT/api.backdropcms.org/www $DOCROOT
        # Download and setup the files directory.
        - wget --http-user=$SANITIZE_USER --http-password=$SANITIZE_PASS -O files.tar.gz $SANITIZE_URL_FILES -P $TUGBOAT_ROOT
        - cd $TUGBOAT_ROOT && tar -xzf files.tar.gz && mv files/ api.backdropcms.org/www/files/
      update:
        # Use the Tugboat-specific Backdrop settings.
        - cp $TUGBOAT_ROOT/.tugboat/settings.local.php $TUGBOAT_ROOT/api.backdropcms.org/www/settings.local.php
        # Generate a unique hash_salt to secure the site.
        - echo "\$settings['hash_salt'] = '$(openssl rand -hex 32)';" >> $TUGBOAT_ROOT/api.backdropcms.org/www/settings.local.php
        # Set appropriate file permissions/ownership.
        - chown -R www-data:www-data $TUGBOAT_ROOT/api.backdropcms.org/www
        - chown -R www-data:www-data $TUGBOAT_ROOT/api.backdropcms.org/config
        - cd $TUGBOAT_ROOT/api.backdropcms.org/www && find files layouts modules themes -type d -exec chmod 2775 {} \;
        - cd $TUGBOAT_ROOT/api.backdropcms.org/www && find files layouts modules themes -type f -exec chmod 0664 {} \;
      build:
        # Update config from live-active.
        - find $TUGBOAT_ROOT/api.backdropcms.org/config/dev-active -mindepth 1 -delete
        - cp -rp $TUGBOAT_ROOT/api.backdropcms.org/config/live-active/* $TUGBOAT_ROOT/api.backdropcms.org/config/dev-active/
  mariadb:
    image: tugboatqa/mariadb:latest
    commands:
      init:
        # Download the database.
        - wget --http-user=$SANITIZE_USER --http-password=$SANITIZE_PASS -O db.sql.gz $SANITIZE_URL_DB -P $TUGBOAT_ROOT
        - cd $TUGBOAT_ROOT && gunzip db.sql.gz
      build:
        # Import the database.
        - mysql -u tugboat -ptugboat tugboat < $TUGBOAT_ROOT/db.sql
        # Change User 1's password (to: BackdropCMS).
        - mysql tugboat -e "UPDATE users SET pass='\$S\$EaFrTogk0mjklJfC8YlxW8f9rZl.fnCk95EjLg5IlUzhhu1CP6zh' WHERE uid=1"
