services:
  php:
    image: tugboatqa/php:7.2-apache
    default: true
    depends: mariadb
    commands:
      init:
        # Add custom PHP settings.
        # - cp $TUGBOAT_ROOT/.tugboat/php.ini /usr/local/etc/php/conf.d/backdrop-php.ini
        # Install PHP 'zip' extension to allow installing Backdrop modules.
        # - docker-php-ext-install zip
        # Enable Apache 'rewrite' module for clean URLs.
        - a2enmod rewrite
        # Get the latest version of api.backdropcms.org.
        - wget https://github.com/backdrop-ops/api.backdropcms.org/archive/main.zip -P $TUGBOAT_ROOT
        - cd $TUGBOAT_ROOT && unzip main.zip && mv api.backdropcms.org-main/ api.backdropcms.org/
        # Link the document root to the expected path.
        - ln -snf $TUGBOAT_ROOT/api.backdropcms.org/www $DOCROOT
        # Download the files directory.
        - wget --http-user=$SANITIZE_USER --http-password=$SANITIZE_PASS -O files.tar.gz $SANITIZE_URL_FILES -P $TUGBOAT_ROOT
        - cd $TUGBOAT_ROOT && tar -xzf files.tar.gz && mv files/ api.backdropcms.org/www/files/
      update:
        # Use the Tugboat-specific Backdrop settings.
        - cp $TUGBOAT_ROOT/.tugboat/settings.local.php $TUGBOAT_ROOT/api.backdropcms.org/www/settings.local.php
        # Generate a unique hash_salt to secure the site.
        - echo "\$settings['hash_salt'] = '$(openssl rand -hex 32)';" >> $TUGBOAT_ROOT/api.backdropcms.org/www/settings.local.php
        # Create the config directories.
        # - mkdir $TUGBOAT_ROOT/www/files/config
        # - mkdir $TUGBOAT_ROOT/www/files/config/active
        # - mkdir $TUGBOAT_ROOT/www/files/config/staging
        # Set appropriate file permissions/ownership.
        - chown -R www-data:www-data $TUGBOAT_ROOT/api.backdropcms.org/www
        - cd $TUGBOAT_ROOT/api.backdropcms.org/www && find files layouts modules themes -type d -exec chmod 2775 {} \;
        - cd $TUGBOAT_ROOT/api.backdropcms.org/www && find files layouts modules themes -type f -exec chmod 0664 {} \;
        # - chmod a+x $TUGBOAT_ROOT/www/core/scripts/install.sh
      build:
        # Update the staging config directory.
        - find $TUGBOAT_ROOT/api.backdropcms.org/config/staging -mindepth 1 -delete
        - cp -rp $TUGBOAT_ROOT/api.backdropcms.org/config/live-active/* $TUGBOAT_ROOT/api.backdropcms.org/config/staging/
        # Update the dev-active config directory.
        - find $TUGBOAT_ROOT/api.backdropcms.org/config/dev-active -mindepth 1 -delete
        - cp -rp $TUGBOAT_ROOT/api.backdropcms.org/config/staging/* $TUGBOAT_ROOT/api.backdropcms.org/config/dev-active/
        # Install Backdrop.
        # - cd $TUGBOAT_ROOT/www && ./core/scripts/install.sh --db-url=mysql://tugboat:tugboat@mariadb/tugboat --account-pass=password
        # Fix config permissions after install.
        # - chown -R www-data:www-data $TUGBOAT_ROOT/www/files/config/active
        # - find $TUGBOAT_ROOT/www/files/config/active -type f -exec chmod 0664 {} \;
        # Generate and display a login URL.
        # - cd $TUGBOAT_ROOT/www && ../.tugboat/auto-login.sh
  mariadb:
    image: tugboatqa/mariadb:latest
    commands:
      init:
        # Configure database for UTF-8: https://api.backdropcms.org/database-configuration#utf8mb4
        # - echo "[mysqld]\ninnodb_large_prefix=true\ninnodb_file_format=barracuda\ninnodb_file_per_table=true" >> /etc/mysql/conf.d/utf8mb.conf
        # Download the database and files directory.
        - wget --http-user=$SANITIZE_USER --http-password=$SANITIZE_PASS -O db.sql.gz $SANITIZE_URL_DB -P $TUGBOAT_ROOT
        - cd $TUGBOAT_ROOT && gunzip db.sql.gz
      build:
        # Drop and re-create the database (needed when rebuilding/reinstalling).
        # - mysqladmin -f drop tugboat && mysqladmin create tugboat
        # Import the database.
        - mysql -u tugboat -ptugboat tugboat < $TUGBOAT_ROOT/db.sql
        # Change User 1's password (to: BackdropCMS).
        - mysql tugboat -e "UPDATE users SET pass='\$S\$EaFrTogk0mjklJfC8YlxW8f9rZl.fnCk95EjLg5IlUzhhu1CP6zh' WHERE uid=1"
